library/urls.py
from django.contrib import admin
from django.urls import path
from library import views
from django.conf.urls import url, include
from django.contrib.auth.views import login
from django.contrib.auth import views as auth_views

app_name='library'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/$', views.books, name='books'),
    url(r'^books/(?P<book_isbn>\w+)/$', views.book, name='book'),
    url(r'^books/(?P<book_isbn>\w+)/addcomment/$', views.addcomment, name='addcomment'),
    url(r'^signin/$', login, {'template_name':'signin.html'}, name='signin'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/profile_edit/$', views.profile_edit, name='profile_edit'),
    url(r'^profile/password_edit/$', auth_views.password_change,
        {'template_name':'password_edit.html', 'post_change_redirect':'/signout/'},
        name='password_edit'),

    url(r'^loans/$', views.loans, name='loans'),
    url(r'^comments/$', views.comments, name='comments'),

    url(r'^deletecomment/(?P<comment_comno>\d+)/$', views.deletecomment, name='deletecomment'),

    url(r'^loan/(?P<storage_stono>\d+)/$', views.loan, name='loan'),
    url(r'^return/(?P<loan_loanno>\d+)/$', views.return_book, name='return_book'),

    url(r'^addbook/$', views.addbook, name='addbook'),
    url(r'^deletebook/(?P<storage_stono>\d+)/$', views.deletebook, name='deletebook'),

    url(r'^loans/renew/(?P<loan_loanno>\d+)/$', views.renew, name='renew'),
    url(r'^reserves/$', views.reserves, name='reserves'),
    url(r'^reserves/(?P<storage_stono>\d+)/$', views.reservebook, name='reservebook'),
    url(r'^reserves/(?P<reserve_reno>\d+)/confirm/$', views.confirmreserve, name='confirmreserve'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path
from library import views
from django.conf.urls import url,include

urlpatterns = [
    #path('admin/', admin.site.urls),

    #path('', views.index),
    #path('books/',views.books),

    url(r'^admin/', admin.site.urls, ),
    url(r'', include('library.urls', namespace='library')),
]

templates/addbook.html
{% extends 'base.html' %}

{% block base %}

                  <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
          <a href="{% url 'library:books' %}" class="breadcrumb">Library</a>
        <a class="breadcrumb">Add a Book</a>
      </div>
    </div>
      </div>
  </nav>

<div class="container">
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card hoverable grey lighten-4">
                <div class="card-content teal-text">
                    <span class="card-title">Add a Book</span>

    <form action="{% url 'library:addbook' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="card-action center">
        <button class="waves-effect waves-light btn" name="reset" type="reset">Reset</button>
        <button class="waves-effect waves-light btn" name="submit">Submit</button>
        </div>
    </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/addcomment.html
{% extends 'base.html' %}

{% block base %}

                      <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
          <a href="{% url 'library:books' %}" class="breadcrumb">Library</a>
          <a href="{% url 'library:book' book.isbn %}" class="breadcrumb">{{ book.title }}</a>
        <a class="breadcrumb">Add a Comment</a>
      </div>
    </div>
      </div>
  </nav>

<div class="container">
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card hoverable grey lighten-4">
                <div class="card-content teal-text">
                    <span class="card-title">Add a Comment</span>

    <form action="{% url 'library:addcomment' book_isbn %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="card-action center">
        <button class="waves-effect waves-light btn" name="reset" type="reset">Reset</button>
        <button class="waves-effect waves-light btn" name="submit" type="submit">Add</button>
        </div>
    </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>infinity Library Management System</title>
    <link rel="icon" href="../static/pic/logo.ico"/>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <link href="/static/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="/static/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="/static/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>


  <script type="text/javascript" src="/static/js/jquery-3.3.1.min.js"></script>
  <script type="text/javascript" src="/static/js/materialize.min.js"></script>

</head>
<body>
  <nav class="teal lighten-3" role="navigation">
    <div class="nav-wrapper container">
      <a href="{% url 'library:index' %}" id="logo-container" class="brand-logo">infinity</a>

      <ul class="right hide-on-med-and-down">
        <li><a href="http://127.0.0.1:8000/admin/"><i class="material-icons">security</i></a></li>
        {% if not user.is_authenticated %}
        <li><a href="{% url 'library:signup' %}"><i class="material-icons">person_add</i></a></li>
        {% endif %}
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'library:signout' %}">
                    <i class="material-icons">clear</i>
                </a>
            </li>
                        <li>
                <a href="{% url 'library:loans' %}">
                    <i class="material-icons">library_add</i>
                </a>
            </li>
                        <li>
                <a href="{% url 'library:comments' %}">
                    <i class="material-icons">comment</i>
                </a>
            </li>
                        <li>
                <a href="{% url 'library:reserves' %}">
                    <i class="material-icons">book</i>
                </a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'library:profile' %}">
                <i class="material-icons">person</i>
            </a>
            {% else %}
            <a href="{% url 'library:signin' %}">
                <i class="material-icons">person_outline</i>
            </a>
            {% endif %}
        </li>
        <li><a href="{% url 'library:books' %}"><i class="material-icons">library_books</i></a>
        </li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
                  <li><a href="http://127.0.0.1:8000/admin/"><i class="material-icons">security</i>Administration</a></li>

        <li><a href="{% url 'library:signup' %}"><i class="material-icons">person_add</i>Sign Up</a></li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'library:signout' %}">
                    <i class="material-icons">clear</i>Sign Out
                </a>
            </li>
                        <li>
                <a href="{% url 'library:loans' %}">
                    <i class="material-icons">library_add</i>Loans List
                </a>
            </li>
                        <li>
                <a href="{% url 'library:comments' %}">
                    <i class="material-icons">comment</i>Comments List
                </a>
            </li>
                        <li>
                <a href="{% url 'library:reserves' %}">
                    <i class="material-icons">book</i>Reserves List
                </a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'library:profile' %}">
                <i class="material-icons">person</i>Profile
            </a>
            {% else %}
            <a href="{% url 'library:signin' %}">
                <i class="material-icons">person_outline</i>Sign In
            </a>
            {% endif %}
        </li>
        <li><a href="{% url 'library:books' %}"><i class="material-icons">library_books</i>Library</a>
        </li>
        <!--the other icons shorted-->
        <li><a href="https://github.com/czhongyu/library-management-system"><i class="material-icons">save</i>Project Repository</a></li>
        <li><a href="https://github.com/czhongyu"><i class="material-icons">save</i>My GitHub</a></li>
      </ul>
      <a href="" data-target="nav-mobile" class="sidenav-trigger right">
          <i class="material-icons">menu</i>
      </a>

    </div>
  </nav>

  <!--unique part-->
  {% block base %}{% endblock %}

</body>
</html>

templates/book.html
{% extends 'base.html' %}

{% block base %}

          <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
        <a href="{% url 'library:books' %}" class="breadcrumb">Library</a>
        <a class="breadcrumb">{{ book.title }}</a>
      </div>
    </div>
      </div>
  </nav>

    <div class="container">
    <div class="row">
    <div class="col s12 m12">
      <div class="card hoverable teal lighten-2">
        <div class="card-content white-text">
          <span class="card-title">{{ book.title }}</span>

            <table class="responsive-table highlight">
                <thead>
                    <tr>
                        <th>ISBN</th>
                        <th>{{ book.isbn }}</th>
                        <th>Authors</th>
                        <th>{{ book.authors }}</th>
                    </tr>
                    <tr>
                        <th>Publisher</th>
                        <th>{{ book.publisher }}</th>
                        <th>Price</th>
                        <th>{{ book.price }}</th>
                    </tr>
                </thead>
            </table>

            </div>
      </div>
    </div>
  </div>
</div>

    <div class="container">
    <div class="row">
    <div class="col s12 m12">
      <div class="card hoverable grey lighten-4">
        <div class="card-content teal-text">
          <span class="card-title">Storages</span>

    <table class="responsive-table highlight">
        <thead>
            <th>No.</th>
            <th>Library</th>
            <th>Due Date</th>
            <th>Reserve</th>
            <th>Loan</th>
            {% if user.is_staff %}
            <th>Delete</th>
            {% endif %}
        </thead>
        <tbody>
            {% for storage in storages %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ storage.lno.lname }}</td>

                {% if storage.available %}
                <td>On the Shelves</td>
                {% else %}
                <td>{{ storage.due_date }}</td>
                {% endif %}

                <td>
                {% if storage.available == 0 %}
                    <a id="download-button" class="btn waves-effect waves-light red lighten-1 disabled">Loaned</a>
                {% elif storage.reservable == 0 %}
                    <a id="download-button" class="btn waves-effect waves-light red lighten-1 disabled">Reserved</a>
                {% else %}
                    <a href="{% url 'library:reservebook' storage.stono %}" id="download-button" class="btn waves-effect waves-light teal lighten-1">Reserve</a>
                {% endif %}
                </td>

                <td>
                    {% if storage.available == 0 %}
                        <a id="download-button" class="btn waves-effect waves-light red lighten-1 disabled">Loaned</a>
                    {% elif storage.reservable == 0 %}
                        <a id="download-button" class="btn waves-effect waves-light red lighten-1 disabled">Reserved</a>
                    {% else %}
                        <a href="{% url 'library:loan' storage.stono %}" id="download-button" class="btn waves-effect waves-light teal lighten-1">Loan</a>
                    {% endif %}
                </td>



                {% if user.is_staff %}
                <td>
                    {% if storage.available == 0 %}
                        <a id="download-button" class="btn waves-effect waves-light red lighten-1 disabled">Loaned</a>
                        {% elif storage.reservable == 0 %}
                        <a id="download-button" class="btn waves-effect waves-light red lighten-1 disabled">Reserved</a>
                        {% else %}
                        <a href="{% url 'library:deletebook' storage.stono %}" id="download-button" class="btn waves-effect waves-light red lighten-1">Delete</a>
                        {% endif %}
                </td>
                {% endif %}

            </tr>
            {% endfor %}
        </tbody>
    </table>

                </div>
      </div>
    </div>
  </div>
</div>

        <div class="container">
    <div class="row">
    <div class="col s12 m12">
      <div class="card hoverable grey lighten-4">
        <div class="card-content teal-text">
          <span class="card-title">Comments</span>

    <table class="responsive-table highlight">
        <thead>
        <tr>
            <th>No.</th>
            <th>id</th>
            <th>text</th>
            <th>delete</th>
        </tr>
        </thead>
        <tbody>
            {% for comment in comments %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ comment.id.username }}</td>
                <td>{{ comment.text }}</td>

                <td>
                    {% if user.is_staff or comment.id.id == user.id %}
                    <a href="{% url 'library:deletecomment' comment.comno %}" id="download-button" class="btn waves-effect waves-light red lighten-1">Delete</a>
                    {% else %}
                    <a id="download-button" class="btn waves-effect waves-light red lighten-1 disabled">Not Authorized</a>
                    {% endif %}
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
                </div>
              <div class="card-action">
          <a href="{% url 'library:addcomment' book.isbn %}">Comment</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/books.html
{% extends 'base.html' %}

{% block base %}

      <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
        <a class="breadcrumb">Library</a>
      </div>
    </div>
      </div>
  </nav>

                    <div class="container">
    <div class="row">
    <div class="col s12 m12">
      <div class="card hoverable grey lighten-4">
        <div class="card-content teal-text">
          <span class="card-title">Search</span>

    <form action="{% url 'library:books' %}" method="post" name="search">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="card-action center">
        <button class="waves-effect waves-light btn" name="reset" type="reset">Reset</button>
        <button class="waves-effect waves-light btn" name="submit">submit</button>
        </div>
    </form>
      </div>
    </div>
  </div>
</div>
    </div>
                <div class="container">
    <div class="row">
    <div class="col s12 m12">
      <div class="card hoverable grey lighten-4">
        <div class="card-content teal-text">
          <span class="card-title">Library</span>

    <table class="responsive-table highlight">
        <thead>
            <tr>
                <th>No.</th>
            <th>title</th>
            <th>isbn</th>
            <th>authors</th>
            <th>publisher</th>
            <th>total</th>
            <th>loaned</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'library:book' book.isbn %}">{{ book.title }}</a>
                </td>
                <td>{{ book.isbn }}</td>
                <td>{{ book.authors }}</td>
                <td>{{ book.publisher }}</td>
                <td>{{ book.count }}</td>
                <td>{{ book.loaned }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
                </div>
      {% if user.is_staff %}
              <div class="card-action">
          <a href="{% url 'library:addbook' %}">Add a Book</a>
        </div>
      {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/comments.html
{% extends 'base.html' %}

{% block base %}

                      <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
          <a href="{% url 'library:profile' %}" class="breadcrumb">Profile</a>
        <a class="breadcrumb">Comments List</a>
      </div>
    </div>
      </div>
  </nav>

    <!--Comments-->

                    <div class="container">
    <div class="row">
    <div class="col s12 m12">
      <div class="card hoverable grey lighten-4">
        <div class="card-content teal-text">
          <span class="card-title">Comments List</span>

    <table class="responsive-table highlight">
        <thead>
        <tr>
            <th>No.</th>
            <th>comno</th>
            <th>isbn</th>
            <th>title</th>
            <th>text</th>
            <th>delete</th>
        </tr>
        </thead>
        <tbody>
            {% for comment in comments %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ comment.comno }}</td>
                <td>{{ comment.isbn.isbn }}</td>
                <td><a href="{% url 'library:book' comment.isbn.isbn %}">{{ comment.isbn.title }}</a></td>
                <td>{{ comment.text }}</td>
                <td>
                    <a href="{% url 'library:deletecomment' comment.comno %}" id="download-button" class="btn waves-effect waves-light red lighten-1">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

      </div>
    </div>
  </div>
</div>
                    </div>
{% endblock %}

templates/loans.html
{% extends 'base.html' %}

{% block base %}

                  <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
          <a href="{% url 'library:profile' %}" class="breadcrumb">Profile</a>
        <a class="breadcrumb">Loans List</a>
      </div>
    </div>
      </div>
  </nav>

    <!--Loans-->

                        <div class="container">
    <div class="row">
    <div class="col s12 m12">
      <div class="card hoverable grey lighten-4">
        <div class="card-content teal-text">
          <span class="card-title">Loans List</span>

    <table class="responsive-table highlight">


        <thead>
            <th>No.</th>

            {% if user.is_staff %}
            <th>username</th>
            {% endif %}

            <th>isbn</th>
            <th>title</th>
            <th>library</th>
            <th>loan_date</th>
            <th>due_date</th>
            <th>renewed</th>
            <th>return_date</th>
            <th>admin_id</th>

            {% if user.is_staff %}
            <th>return</th>
            {% endif %}
        </thead>
        <tbody>
            {% for loan in loans %}
            <tr>
                <td>{{ forloop.counter }}</td>
                {% if user.is_staff %}
                <td>{{ loan.id.username }}</td>
                {% endif %}
                <td>{{ loan.stono.isbn.isbn }}</td>
                <td><a href="{% url 'library:book' loan.stono.isbn.isbn %}">{{ loan.stono.isbn.title }}</a></td>
                <td>{{ loan.stono.lno.lname }}</td>
                <td>{{ loan.loan_date }}</td>
                <td>{{ loan.due_date }}</td>

                <td>
                {% if loan.renewed %}
                <a id="download-button" class="btn disabled waves-effect waves-light teal lighten-1">Renewed</a>
                {% elif loan.return_date != None %}
                    <a id="download-button" class="btn disabled waves-effect waves-light teal lighten-1">Returned</a>
                    {% else %}
                <a href="{% url 'library:renew' loan.loanno %}" id="download-button" class="btn waves-effect waves-light teal lighten-1">Renew Now</a>
                {% endif %}
                </td>

                <td>{{ loan.return_date }}</td>
                <td>{{ loan.admin_id }}</td>

                {% if user.is_staff %}
                    {% if loan.return_date == None %}
                    <td>
                        <a href="{% url 'library:return_book' loan.loanno %}" id="download-button" class="btn waves-effect waves-light teal lighten-1">Return</a>
                    </td>
                    {% else %}
                    <td>
                        <a id="download-button" class="btn disabled waves-effect waves-light teal lighten-1">Returned</a>
                    </td>
                    {% endif %}
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
      </div>
    </div>
  </div>
</div>
                    </div>

{% endblock %}

templates/password_edit.html
{% extends 'base.html' %}

{% block base %}


                  <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
          <a href="{% url 'library:profile' %}" class="breadcrumb">Profile</a>
        <a class="breadcrumb">Change Password</a>
      </div>
    </div>
      </div>
  </nav>

<div class="container">
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card hoverable grey lighten-4">
                <div class="card-content teal-text">
                    <span class="card-title">Change Password</span>

    <form method="post" action="{% url 'library:password_edit' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="card-action center">
        <button class="waves-effect waves-light btn" name="reset" type="reset">Reset</button>
        <button class="waves-effect waves-light btn" name="submit">Submit</button>
        <input type="hidden" name="next" value="{% url 'library:signout' %}" />
        </div>
    </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/profile_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block base %}


                  <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
          <a href="{% url 'library:profile' %}" class="breadcrumb">Profile</a>
        <a class="breadcrumb">Update Profile</a>
      </div>
    </div>
      </div>
  </nav>

<div class="container">
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card hoverable grey lighten-4">
                <div class="card-content teal-text">
                    <span class="card-title">Update Profile</span>

    <form action="{% url 'library:profile_edit' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="card-action center">
            <button class="waves-effect waves-light btn" name="reset" type="reset">Reset</button>
            <button class="waves-effect waves-light btn" name="submit">Update</button>
        </div>
    </form>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/reservebook.html
{% extends 'base.html' %}

{% block base %}

          <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
        <a href="{% url 'library:books' %}" class="breadcrumb">Library</a>
         <a href="{% url 'library:book' storage.isbn.isbn %}" class="breadcrumb">{{ storage.isbn.title }}</a>
        <a class="breadcrumb">Reserve a Book</a>
      </div>
    </div>
      </div>
  </nav>

<div class="container">
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card hoverable grey lighten-4">
                <div class="card-content teal-text">
                    <span class="card-title">Reserve a Book</span>

    <form action="{% url 'library:reservebook' storage_stono %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="card-action center">
        <button class="waves-effect waves-light btn" name="reset" type="reset">Reset</button>
        <button class="waves-effect waves-light btn" name="submit">Reserve</button>
        </div>
    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/reserves.html
{% extends 'base.html' %}

{% block base %}

              <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
        <a href="{% url 'library:profile' %}" class="breadcrumb">Profile</a>
        <a class="breadcrumb">Reserves List</a>
      </div>
    </div>
      </div>
  </nav>

                        <div class="container">
    <div class="row">
    <div class="col s12 m12">
      <div class="card hoverable grey lighten-4">
        <div class="card-content teal-text">
          <span class="card-title">Reserves List</span>

    <table class="responsive-table highlight">
        <thead>
            <th>No.</th>
            <th>lname</th>
            <th>stono</th>
            <th>title</th>
            <th>id</th>
            <th>reno</th>
            <th>admin_id</th>
            {% if user.is_staff %}
            <th>Confirm</th>
            {% endif %}
        </thead>
        <tbody>
            {% for reserve in reserves %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ reserve.lno.lname }}</td>
                <td>{{ reserve.stono.stono }}</td>
                <td><a href="{% url 'library:book' reserve.stono.isbn.isbn %}">{{ reserve.stono.isbn.title }}</a></td>
                <td>{{ reserve.id.id }}</td>
                <td>{{ reserve.reno }}</td>
                <td>{{ reserve.admin_id }}</td>

                {% if user.is_staff %}
                <td>
                    {% if reserve.admin_id == None %}
                    <a href="{% url 'library:confirmreserve' reserve.reno %}" id="download-button" class="btn waves-effect waves-light red lighten-1">Confirm</a>
                    {% else %}
                    <a id="download-button" class="btn disabled waves-effect waves-light red lighten-1">Confirmed</a>
                    {% endif %}
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
      </div>
    </div>
  </div>
</div>
                    </div>
{% endblock %}

templates/signin.html
{% extends 'base.html' %}

{% block base %}

                  <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
        <a class="breadcrumb">Sign In</a>
      </div>
    </div>
      </div>
  </nav>

<div class="container">
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card hoverable grey lighten-4">
                <div class="card-content teal-text">
                    <span class="card-title">Sign In</span>


    {% if form.errors %}
    <p>Your username and password didn't match.Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'library:signin' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <form action="{% url 'library:profile_edit' %}" method="post">
            <div class="card-action center">
        <button class="waves-effect waves-light btn" name="reset" type="reset">Reset</button>
        <button class="waves-effect waves-light btn" name="submit">Sign In</button>
        <input type="hidden" name="next" value="{% url 'library:profile' %}" />
                    <p>No account?</p>
                <a href="{% url 'library:signup' %}" id="download-button" class="btn waves-effect waves-light teal lighten-1">Sign Up</a>
            </div>
        </form>
    </form>




                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block base %}

                      <nav class="red lighten-3">
      <div class="row">
    <div class="nav-wrapper ">
      <div class="col s12 m6 offset-m2">
        <a href="{% url 'library:index' %}" class="breadcrumb">Main</a>
        <a class="breadcrumb">Sign Up</a>
      </div>
    </div>
      </div>
  </nav>

<div class="container">
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card hoverable grey lighten-4">
                <div class="card-content teal-text">
                    <span class="card-title">Sign Up</span>

    <form method="post" action="{% url 'library:signup' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="card-action center">
        <button class="waves-effect waves-light btn" name="reset" type="reset">Reset</button>
        <button class="waves-effect waves-light btn" name="submit">Sign Up</button>
        <input type="hidden" name="next" value="{% url 'library:index' %}" />
        </div>
    </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}